libfprint: Device discovery
Device discovery
These functions allow you to scan the system for supported fingerprint scanning hardware.
Functions
struct fp_dscv_dev ** fp_discover_devs (void)
Scans the system and returns a list of discovered devices.
void fp_dscv_devs_free (struct fp_dscv_dev **devs)
Free a list of discovered devices.
struct fp_driver * fp_dscv_dev_get_driver (struct fp_dscv_dev *dev)
Gets the driver for a discovered device.
uint32_t fp_dscv_dev_get_devtype (struct fp_dscv_dev *dev)
Gets the devtype for a discovered device.
int fp_dscv_dev_supports_print_data (struct fp_dscv_dev *dev, struct fp_print_data *data)
Determines if a specific stored print appears to be compatible with a discovered device.
int fp_dscv_dev_supports_dscv_print (struct fp_dscv_dev *dev, struct fp_dscv_print *data)
Determines if a specific discovered print appears to be compatible with a discovered device.
struct fp_dscv_dev * fp_dscv_dev_for_print_data (struct fp_dscv_dev **devs, struct fp_print_data *data)
Searches a list of discovered devices for a device that appears to be compatible with a stored print.
struct fp_dscv_dev * fp_dscv_dev_for_dscv_print (struct fp_dscv_dev **devs, struct fp_dscv_print *print)
Searches a list of discovered devices for a device that appears to be compatible with a discovered print.
Detailed Description
These functions allow you to scan the system for supported fingerprint scanning hardware.
This is your starting point when integrating libfprint into your software.
When you've identified a discovered device that you would like to control, you can open it with fp_dev_open(). Note that discovered devices may no longer be available at the time when you want to open them, for example the user may have unplugged the device.
Function Documentation
struct fp_dscv_dev** fp_discover_devs (void)
Scans the system and returns a list of discovered devices.
This is your entry point into finding a fingerprint reader to operate.
Returns
a NULL-terminated list of discovered devices. Must be freed with fp_dscv_devs_free() after use.
void fp_dscv_devs_free (struct fp_dscv_dev ** devs)
Free a list of discovered devices.
This function destroys the list and all discovered devices that it included, so make sure you have opened your discovered device before freeing the list.
Parameters
devs the list of discovered devices. If NULL, function simply returns.
struct fp_driver* fp_dscv_dev_get_driver (struct fp_dscv_dev * dev)
Gets the driver for a discovered device.
Parameters
dev the discovered device
Returns
the driver backing the device
uint32_t fp_dscv_dev_get_devtype (struct fp_dscv_dev * dev)
Gets the devtype for a discovered device.
Parameters
dev the discovered device
Returns
the devtype of the device
int fp_dscv_dev_supports_print_data (struct fp_dscv_dev * dev, struct fp_print_data * data)
Determines if a specific stored print appears to be compatible with a discovered device.
Parameters
dev the discovered device
data the print for compatibility checking
Returns
1 if the print is compatible with the device, 0 otherwise
Referenced by fp_dscv_dev_for_print_data().
int fp_dscv_dev_supports_dscv_print (struct fp_dscv_dev * dev, struct fp_dscv_print * data)
Determines if a specific discovered print appears to be compatible with a discovered device.
Parameters
dev the discovered device
data the discovered print for compatibility checking
Returns
1 if the print is compatible with the device, 0 otherwise
Referenced by fp_dscv_dev_for_dscv_print().
struct fp_dscv_dev* fp_dscv_dev_for_print_data (struct fp_dscv_dev ** devs, struct fp_print_data * data)
Searches a list of discovered devices for a device that appears to be compatible with a stored print.
Parameters
devs a list of discovered devices
data the print under inspection
Returns
the first discovered device that appears to support the print, or NULL if no apparently compatible devices could be found
References fp_dscv_dev_supports_print_data().
struct fp_dscv_dev* fp_dscv_dev_for_dscv_print (struct fp_dscv_dev ** devs, struct fp_dscv_print * print)
Searches a list of discovered devices for a device that appears to be compatible with a discovered print.
Parameters
devs a list of discovered devices
print the print under inspection
Returns
the first discovered device that appears to support the print, or NULL if no apparently compatible devices could be found
References fp_dscv_dev_supports_dscv_print().